Adding a health checker
prjctr-imazur/video-service pull request #2
Opened 2021-11-11 21:16 UTC by geekartisans

Adding a health checker
Adding an error handler 
Separate routes

2021-11-12 11:03 UTC, welikoiwanenko requested changes

2021-11-12 11:03 UTC, welikoiwanenko commented on src/api/routes/videos.js
> +    }
Теперь это можно отрефакторить и написать в 2 строки, учитывая добавление errorHandler

2021-11-12 11:06 UTC, welikoiwanenko commented on package.json
> +    "koa-body-parser": "0.2.1",
?
Во-первых, этот пакет в последний раз коммитился 7 лет назад
Во-вторых, его актуальная версия - 1.1.2
Крайне советаю использовать популярный koa-bodyparser

2021-11-12 16:00 UTC, geekartisans commented on src/api/routes/videos.js
> +    }
спасибо, исправил

2021-11-12 16:04 UTC, geekartisans commented on package.json
> +    "koa-body-parser": "0.2.1",
обновил пакет на `koa-bodyparser`

2021-11-13 09:13 UTC, welikoiwanenko approved these changes

2021-11-18 18:35 UTC, merged