Adding a config and a logger services
prjctr-imazur/video-service pull request #3
Opened 2021-11-18 19:07 UTC by geekartisans

2021-11-19 18:19 UTC, welikoiwanenko requested changes
Выглядит 🔥🔥🔥🔥, особенно ConfigService!
Есть пару вопросов

2021-11-19 18:19 UTC, welikoiwanenko commented on src/index.js
> +  port: configService.get('APP_PORT'),
ConfigService - инетерсная идея, но тогда не стоит экспоузить переменные окружения наружу, всё должно быть описано внутри самого ConfigService (как, к примеру APP_LOG_LEVEL)

2021-11-19 18:19 UTC, welikoiwanenko commented on src/services/LoggerService.js
> +module.exports = loggerServiceInstance();
Каждый раз создаётся новый логгер?

2021-11-19 18:21 UTC, welikoiwanenko commented on package.json
> +    "prestart": "shx cp -n .env.default .env",
Эта команда перетрёт .env. Идея пакета `dotenv-defaults` - файл .env дополняет, а не заменяет .env.defaults
Обрати внимание на названия.

2021-12-16 22:42 UTC, geekartisans commented on package.json
> +    "prestart": "shx cp -n .env.default .env",
удалил скрипт `prestart`, а также переименовал `.env.default` -> `.env.defaults`

2021-12-16 22:45 UTC, geekartisans commented on src/services/LoggerService.js
> +module.exports = loggerServiceInstance();
переделал конфиг, но и в таком случае новый логег не создавался, я проверял, добавил console.log в функцию `loggerServiceInstance` при подключении логера в новый файл метод, в консоль ничего не выводилось

2021-12-16 22:46 UTC, geekartisans commented on src/index.js
> +  port: configService.get('APP_PORT'),
переделал ConfigService, убрал экспорт переменных, описываю все внутри конфига

2021-12-17 12:00 UTC, welikoiwanenko commented on .env.defaults
> +logLevel=debug
Переменные окружения называются капсом (HOST, PORT, LOG_LEVEL)
Пофикси это плиз во всех сервисах перед мержем

2021-12-17 14:12 UTC, geekartisans commented on .env.defaults
> +logLevel=debug
поправил

2021-12-17 14:20 UTC, merged